trigger:
  - main

variables:
  tf_root: "$(Build.SourcesDirectory)/azure/03-terraform-cicd/src"

  # backend (state)
  backend_service_connection: "azure-connection"
  backend_storage_account: "stiacdevtfstate001"
  backend_container: "tfstate"
  backend_key: "webapp-dev.terraform.tfstate"

  # terraform version
  terraform_version: "latest"

stages:
  - stage: plan
    displayName: Terraform Plan
    jobs:
      - job: plan
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: "$(terraform_version)"

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: "$(tf_root)"
              backendServiceArm: "$(backend_service_connection)"
              backendAzureRmUseEntraIdForAuthentication: true
              backendAzureRmStorageAccountName: "$(backend_storage_account)"
              backendAzureRmContainerName: "$(backend_container)"
              backendAzureRmKey: "$(backend_key)"

          # - script: docker run ... checkov ...
          #   displayName: Checkov scan

          - task: TerraformTask@5
            name: terraformPlan
            displayName: Terraform Plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: "$(tf_root)"
              commandOptions: "-out tfplan"
              environmentServiceNameAzureRM: "$(backend_service_connection)"

          - task: CopyFiles@2
            displayName: Create Module Artifact
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: |
                **/*
                !.terraform/**/*
                !.git/**/*
                !**/.terraform/**/*
                !**/.git/**/*
              TargetFolder: "$(Build.ArtifactsStagingDirectory)"
              CleanTargetFolder: true
              OverWrite: true

          - task: PublishPipelineArtifact@1
            displayName: Publish Module Artifact
            inputs:
              targetPath: "$(Build.ArtifactsStagingDirectory)"
              artifact: terraformModule
              publishLocation: pipeline

  - stage: apply
    displayName: Terraform Apply
    dependsOn: plan
    condition: and(succeeded(), eq(dependencies.plan.outputs['plan.terraformPlan.changesPresent'], 'true'))
    jobs:
      - job: apply
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Module Artifact
            inputs:
              source: current
              artifactName: terraformModule
              targetPath: "$(Build.SourcesDirectory)"

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: "$(terraform_version)"

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: "$(tf_root)"
              backendServiceArm: "$(backend_service_connection)"
              backendAzureRmUseEntraIdForAuthentication: true
              backendAzureRmStorageAccountName: "$(backend_storage_account)"
              backendAzureRmContainerName: "$(backend_container)"
              backendAzureRmKey: "$(backend_key)"

          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: "$(tf_root)"
              commandOptions: "tfplan"
              environmentServiceNameAzureRM: "$(backend_service_connection)"
